name: 导出Keep镜像离线Tar包
on:
  workflow_dispatch: # 手动一键执行
  schedule:
    - cron: "0 17 * * *" # 每日凌晨自动打包

jobs:
  export_tar:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取官方Keep镜像
        run: |
          docker pull us-central1-docker.pkg.dev/keephq/keep/keep-api:latest
          docker pull us-central1-docker.pkg.dev/keephq/keep/keep-ui:latest

      - name: 导出为离线tar文件
        run: |
          docker save -o keep-api.tar us-central1-docker.pkg.dev/keephq/keep/keep-api:latest
          docker save -o keep-ui.tar us-central1-docker.pkg.dev/keephq/keep/keep-ui:latest

      - name: 上传打包文件到任务产物
        uses: actions/upload-artifact@v4
        with:
          name: keep-offline-images
          path: |
            keep-api.tar
            keep-ui.tar
